### ISSUE TITLE
Unable to get gold price

### ISSUE THREAD

**Issue by skdnp** [conradreisch/EODDataPortfolio-MoneyMoney#1]
Hello.
I'm trying to make an account for physical gold, but somehow it doesn't work properly.
Viewing at the source of https://eoddata.com/stockquote/FOREX/XAUEUR.htm, I can't spot any difference in the html compared to e.g. the AAPL from the examples.
However using "FOREX/XAUEUR(3.286) [EUR]" fails to compute a value for the account.
Any idea what might go wrong? Screenshot attached.

![Screen Shot 2021-04-21 at 12 12 19](https://user-images.githubusercontent.com/65280426/115536957-9b5a9400-a29a-11eb-8bd6-26c7532dd481.jpg)

**Comment by dark-m0de** [comment]
Thanks for providing the feedback. I'm investigating it right now. My first assumption is that the number from that specific FOREX has a comma instead of a dot.
I'll write again when I have pushed a fixed version with a mm signature.
<img width="508" alt="image" src="https://user-images.githubusercontent.com/40696850/115576869-3156e480-a2c4-11eb-91ee-1a55bf8faead.png">

**Comment by skdnp** [comment]
Yeah, the comma was instantly my vague suspicion as well. Guess that tonumber lua-internal isn't prepared for that?
Thanks for the fast response!

**Comment by dark-m0de** [comment]
Just received the signed version and merged it. Solution was to remove comma signs from stock price strings.
"FOREX/XAUEUR(3.286)[EUR]" is working now.

**Comment by skdnp** [comment]
10/10 githubber. Sehr zu empfehlen, gerne wieder :)
