### ISSUE TITLE
Currency conversion not working properly 

### ISSUE THREAD

**Issue by iSchorsch** [conradreisch/EODDataPortfolio-MoneyMoney#3]
Thank you for your great plug in! I really like it a lot!

There is a bug:

I enter:
NASDAQ/AAPL(1)[EUR] 
result: 161€
but the real value is currently $161 not 161€
The EUR value is 145,35 € (which is not displayed)

conclusion: currency conversion is not working properly, instead the dollar value is displayed.

**Comment by dark-m0de** [comment]
Did you try „NASDAQ/AAPL(1)[USD]“ ?

**Comment by iSchorsch** [comment]
Thank you for that hint. I did try that and it displays a better value, closer to the correct on in EURs.
I don't understand. Isn't it now supposed to be displayed in USD? Is the currency conversion taken care of properly?
I like to see AAPL traded in USD and the value displayed in MoneyMoney in EUR. So your syntax is the right one for that?

**Comment by dark-m0de** [comment]
The program logic is converting everything to be displayed in EUR (as standard). 
Since EODData unfortunately does not tell you the source currency of the ticker, I added the currency bracket feature.
(See missing currency info e.g. in http://eoddata.com/stockquote/NASDAQ/AAPL.htm) 
Afterwards the extension is converting from source currency X to EUR, which is displayed in MoneyMoney. The conversion is also done with the EODData (see http://eoddata.com/stockquote/FOREX/EURUSD.htm).

Therefore the displayed value refers to the last end-of-day info from the stock market and from FOREX. Additionally, there might be little rounding errors depending on the FOREX data precision.

Happy to hear that you enjoy the extension. Is there anything I can improve from your perspective?

**Comment by iSchorsch** [comment]
This is great news! Thanks for clarifying/explaining how your wonderful lua-plug in works.
A great "feature" would be the ability to add stock with buying date and then having the development of the stock in perspective. Gain/loss from buying day. Also restocking stock would be nice, like buying more stock from the same company and having that shown in the list.
btw: you can close the ticket, since the issue is resolved. Thank you!

**Comment by dark-m0de** [comment]
Well, I think you can do most of this already today.
- If you do a right click on the stock in MoneyMoney, you can add a purchasing price and gains/losses are displayed accordingly. I'm not loading historical data. But if you update MM regularly, you will have the history here.
- If you further add stock, you can either add this as an additional ticker (to track it separately) or just update the ticker (lets say 200 shares instead of 100) and update the average purchasing price.

I'm closing the issue. Feel free to let me know in case there is anything I can help you with.
